---
title: "RPart"
author: "Terence Carey"
date: "November 20, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=FALSE, echo = FALSE}
library(caret)
library(rpart)
d <- read.csv("googleplaystore.csv")
d <- d[d$Size != 'Varies with device',]
d <- d[d$Current.Ver != 'Varies with device',]
d <- d[!is.nan(d$Current.Ver),]
d <- d[!is.nan(d$Rating),]
d <- d[!is.nan(d$Price),]
d <- d[!is.nan(d$Type),]
d$Installs <- gsub(',', '', d$Installs)
d$Installs <- gsub('\\+', '', d$Installs)
d$Installs <- as.numeric(as.character((d$Installs)))
d$Current.Ver <- gsub('[a-z_()A-Z\\-\\+]', '', d$Current.Ver)
d$Price <- gsub('\\$', '', d$Price)
d$Price <- as.numeric(as.character((d$Price)))
d$Updates <- ifelse(d$Current.Ver >= 2 , ifelse(d$Current.Ver >= 4, 2, 1), 0)
d <- subset(d, select = c('App','Category','Rating','Reviews','Size','Installs','Type','Price','Content.Rating','Last.Updated','Updates','Android.Ver' ))
d <- d[order(d$Installs, decreasing = TRUE),]
d <- tail(d, nrow(d) -34)
dpaid <- d[d$Type == 'Paid',]
dfree <- d[d$Type == 'Free',]
write.csv(d, file = "testing.csv")
library(caret)
d <- na.omit(d)
set.seed(4000)
dmv = dummyVars(~Category + Reviews + Rating, data = d)
features = predict(dmv,d)
y = d$Installs

ctr <- trainControl(method = "cv", number = 4, classProbs = F, search = "random")
fit <- train(features,y , method = 'rpart', trControl = ctr, tuneLength = 10)

```


##Linear Model stuff
```{r}

library(caret)
set.seed(100)


d_train <- d[sample(1:nrow(d), 5500,
   replace=FALSE),] 
d_test = d[!(d$App %in% d_train$App),]

dmv = dummyVars(~Reviews + Category + Content.Rating + Updates + Size + Type, data=d_train)
features = predict(dmv, d_train)
y <- d_train$Rating
ctr = trainControl(method = "cv", number = 4, classProbs =F, search = "random")
fit3 <- train(features, y, preProcess=c("center", "scale", "pca", "zv", "nzv"),
             method = 'glm',
             trControl = ctr, tuneLength = 10)
fit3

dmv = dummyVars(~Reviews + Category + Updates + Type + Rating, data=d_train)
features = predict(dmv, d_train)
y <- d_train$Installs
ctr = trainControl(method = "cv", number = 4, classProbs =F, search = "random")
fit3 <- train(features, y, preProcess=c("center", "scale", "pca", "zv", "nzv"),
             method = 'glm',
             trControl = ctr, tuneLength = 10)
fit3
```
